/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccessUsersUpdateTokenResponseData {

    /// The new API token secret
    #[serde(rename = "secret", skip_serializing_if = "Option::is_none")]
    pub secret: Option<String>,


}

impl AccessUsersUpdateTokenResponseData {
    pub fn new() -> AccessUsersUpdateTokenResponseData {
        AccessUsersUpdateTokenResponseData {
            
            secret: None,
            
        }
    }
}


