/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccessOpenidCreateAuthUrlRequest {

    /// Realm name.
    #[serde(rename = "realm")]
    pub realm: String,

    /// Redirection Url. The client should set this to used server url.
    #[serde(rename = "redirect-url")]
    pub redirect_url: String,


}

impl AccessOpenidCreateAuthUrlRequest {
    pub fn new(realm: String, redirect_url: String) -> AccessOpenidCreateAuthUrlRequest {
        AccessOpenidCreateAuthUrlRequest {
            
            realm,
            
            redirect_url,
            
        }
    }
}


