/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AdminDatastoreGetStatusResponseDataS3Statistics : Statistics specific to the S3 backend
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AdminDatastoreGetStatusResponseDataS3Statistics {

    /// Delete requests
    #[serde(rename = "delete")]
    pub delete: i64,

    /// Total downloaded (bytes).
    #[serde(rename = "downloaded")]
    pub downloaded: i64,

    /// Get requests
    #[serde(rename = "get")]
    pub get: i64,

    /// Head requests
    #[serde(rename = "head")]
    pub head: i64,

    /// Post requests
    #[serde(rename = "post")]
    pub post: i64,

    /// Put requests
    #[serde(rename = "put")]
    pub put: i64,

    /// Total uploaded (bytes).
    #[serde(rename = "uploaded")]
    pub uploaded: i64,


}

impl AdminDatastoreGetStatusResponseDataS3Statistics {
    /// Statistics specific to the S3 backend
    pub fn new(delete: i64, downloaded: i64, get: i64, head: i64, post: i64, put: i64, uploaded: i64) -> AdminDatastoreGetStatusResponseDataS3Statistics {
        AdminDatastoreGetStatusResponseDataS3Statistics {
            
            delete,
            
            downloaded,
            
            get,
            
            head,
            
            post,
            
            put,
            
            uploaded,
            
        }
    }
}


