/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AdminDatastoreGetGroupsResponseDataInner {

    /// Number of contained snapshots
    #[serde(rename = "backup-count")]
    pub backup_count: i64,

    /// Backup ID.
    #[serde(rename = "backup-id")]
    pub backup_id: String,

    /// Backup types.
    #[serde(rename = "backup-type")]
    pub backup_type: models::PbsBackupTypeEnum,

    /// The first line from group \"notes\"
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,

    /// List of contained archive files.
    #[serde(rename = "files")]
    pub files: Vec<String>,

    /// Backup time (Unix epoch.)
    #[serde(rename = "last-backup")]
    pub last_backup: i64,

    /// Authentication ID
    #[serde(rename = "owner", skip_serializing_if = "Option::is_none")]
    pub owner: Option<String>,


}

impl AdminDatastoreGetGroupsResponseDataInner {
    pub fn new(backup_count: i64, backup_id: String, backup_type: models::PbsBackupTypeEnum, files: Vec<String>, last_backup: i64) -> AdminDatastoreGetGroupsResponseDataInner {
        AdminDatastoreGetGroupsResponseDataInner {
            
            backup_count,
            
            backup_id,
            
            backup_type,
            
            comment: None,
            
            files,
            
            last_backup,
            
            owner: None,
            
        }
    }
}


