/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AdminDatastoreGetGcResponseDataCacheStats : Garbage collection cache statistics
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AdminDatastoreGetGcResponseDataCacheStats {

    /// Number of atime update cache hits
    #[serde(rename = "hits")]
    pub hits: i64,

    /// Number of atime update cache misses
    #[serde(rename = "misses")]
    pub misses: i64,


}

impl AdminDatastoreGetGcResponseDataCacheStats {
    /// Garbage collection cache statistics
    pub fn new(hits: i64, misses: i64) -> AdminDatastoreGetGcResponseDataCacheStats {
        AdminDatastoreGetGcResponseDataCacheStats {
            
            hits,
            
            misses,
            
        }
    }
}


