/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AdminVerifyGetVerifyResponseDataInner {

    /// Comment.
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,

    /// Job ID.
    #[serde(rename = "id")]
    pub id: String,

    /// Do not verify backups that are already verified if their verification is not outdated.
    #[serde(rename = "ignore-verified", skip_serializing_if = "Option::is_none")]
    pub ignore_verified: Option<bool>,

    /// Endtime of the last run.
    #[serde(rename = "last-run-endtime", skip_serializing_if = "Option::is_none")]
    pub last_run_endtime: Option<i64>,

    /// Result of the last run.
    #[serde(rename = "last-run-state", skip_serializing_if = "Option::is_none")]
    pub last_run_state: Option<String>,

    /// Task UPID of the last run.
    #[serde(rename = "last-run-upid", skip_serializing_if = "Option::is_none")]
    pub last_run_upid: Option<String>,

    /// How many levels of namespaces should be operated on (0 == no recursion)
    #[serde(rename = "max-depth", skip_serializing_if = "Option::is_none")]
    pub max_depth: Option<i32>,

    /// Estimated time of the next run (UNIX epoch).
    #[serde(rename = "next-run", skip_serializing_if = "Option::is_none")]
    pub next_run: Option<i64>,

    /// Namespace.
    #[serde(rename = "ns", skip_serializing_if = "Option::is_none")]
    pub ns: Option<String>,

    /// Days after that a verification becomes outdated. (0 is deprecated)'
    #[serde(rename = "outdated-after", skip_serializing_if = "Option::is_none")]
    pub outdated_after: Option<i64>,

    /// The number of threads to use for reading chunks in verify job.
    #[serde(rename = "read-threads", skip_serializing_if = "Option::is_none")]
    pub read_threads: Option<i32>,

    /// Run verify job at specified schedule.
    #[serde(rename = "schedule", skip_serializing_if = "Option::is_none")]
    pub schedule: Option<String>,

    /// Datastore name.
    #[serde(rename = "store")]
    pub store: String,

    /// The number of threads to use for verifying chunks in verify job.
    #[serde(rename = "verify-threads", skip_serializing_if = "Option::is_none")]
    pub verify_threads: Option<i32>,


}

impl AdminVerifyGetVerifyResponseDataInner {
    pub fn new(id: String, store: String) -> AdminVerifyGetVerifyResponseDataInner {
        AdminVerifyGetVerifyResponseDataInner {
            
            comment: None,
            
            id,
            
            ignore_verified: None,
            
            last_run_endtime: None,
            
            last_run_state: None,
            
            last_run_upid: None,
            
            max_depth: None,
            
            next_run: None,
            
            ns: None,
            
            outdated_after: None,
            
            read_threads: None,
            
            schedule: None,
            
            store,
            
            verify_threads: None,
            
        }
    }
}


