/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AdminDatastoreCreateNamespaceRequest {

    /// The name of the new namespace to add at the parent.
    #[serde(rename = "name")]
    pub name: String,

    /// Namespace.
    #[serde(rename = "parent", skip_serializing_if = "Option::is_none")]
    pub parent: Option<String>,


}

impl AdminDatastoreCreateNamespaceRequest {
    pub fn new(name: String) -> AdminDatastoreCreateNamespaceRequest {
        AdminDatastoreCreateNamespaceRequest {
            
            name,
            
            parent: None,
            
        }
    }
}


