/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AdminDatastoreGetStatusResponseDataGcStatus : Garbage collection status.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AdminDatastoreGetStatusResponseDataGcStatus {

    #[serde(rename = "cache-stats", skip_serializing_if = "Option::is_none")]
    pub cache_stats: Option<Box<models::AdminDatastoreGetGcResponseDataCacheStats>>,

    /// Bytes used on disk.
    #[serde(rename = "disk-bytes")]
    pub disk_bytes: i64,

    /// Chunks used on disk.
    #[serde(rename = "disk-chunks")]
    pub disk_chunks: i64,

    /// Sum of bytes referred by index files.
    #[serde(rename = "index-data-bytes")]
    pub index_data_bytes: i64,

    /// Number of processed index files.
    #[serde(rename = "index-file-count")]
    pub index_file_count: i64,

    /// Sum of pending bytes (pending removal - kept for safety).
    #[serde(rename = "pending-bytes")]
    pub pending_bytes: i64,

    /// Number of pending chunks (pending removal - kept for safety).
    #[serde(rename = "pending-chunks")]
    pub pending_chunks: i64,

    /// Number of chunks marked as .bad by verify that have been removed by GC.
    #[serde(rename = "removed-bad")]
    pub removed_bad: i64,

    /// Sum of removed bytes.
    #[serde(rename = "removed-bytes")]
    pub removed_bytes: i64,

    /// Number of removed chunks.
    #[serde(rename = "removed-chunks")]
    pub removed_chunks: i64,

    /// Number of chunks still marked as .bad after garbage collection.
    #[serde(rename = "still-bad")]
    pub still_bad: i64,

    /// Unique Process/Task Identifier
    #[serde(rename = "upid", skip_serializing_if = "Option::is_none")]
    pub upid: Option<String>,


}

impl AdminDatastoreGetStatusResponseDataGcStatus {
    /// Garbage collection status.
    pub fn new(disk_bytes: i64, disk_chunks: i64, index_data_bytes: i64, index_file_count: i64, pending_bytes: i64, pending_chunks: i64, removed_bad: i64, removed_bytes: i64, removed_chunks: i64, still_bad: i64) -> AdminDatastoreGetStatusResponseDataGcStatus {
        AdminDatastoreGetStatusResponseDataGcStatus {
            
            cache_stats: None,
            
            disk_bytes,
            
            disk_chunks,
            
            index_data_bytes,
            
            index_file_count,
            
            pending_bytes,
            
            pending_chunks,
            
            removed_bad,
            
            removed_bytes,
            
            removed_chunks,
            
            still_bad,
            
            upid: None,
            
        }
    }
}


