/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AdminDatastoreCreatePruneRequest {

    /// Backup ID.
    #[serde(rename = "backup-id")]
    pub backup_id: String,

    /// Backup types.
    #[serde(rename = "backup-type")]
    pub backup_type: models::PbsBackupTypeEnum,

    /// Just show what prune would do, but do not delete anything.
    #[serde(rename = "dry-run", skip_serializing_if = "Option::is_none")]
    pub dry_run: Option<bool>,

    /// Number of daily backups to keep.
    #[serde(rename = "keep-daily", skip_serializing_if = "Option::is_none")]
    pub keep_daily: Option<i64>,

    /// Number of hourly backups to keep.
    #[serde(rename = "keep-hourly", skip_serializing_if = "Option::is_none")]
    pub keep_hourly: Option<i64>,

    /// Number of backups to keep.
    #[serde(rename = "keep-last", skip_serializing_if = "Option::is_none")]
    pub keep_last: Option<i64>,

    /// Number of monthly backups to keep.
    #[serde(rename = "keep-monthly", skip_serializing_if = "Option::is_none")]
    pub keep_monthly: Option<i64>,

    /// Number of weekly backups to keep.
    #[serde(rename = "keep-weekly", skip_serializing_if = "Option::is_none")]
    pub keep_weekly: Option<i64>,

    /// Number of yearly backups to keep.
    #[serde(rename = "keep-yearly", skip_serializing_if = "Option::is_none")]
    pub keep_yearly: Option<i64>,

    /// Namespace.
    #[serde(rename = "ns", skip_serializing_if = "Option::is_none")]
    pub ns: Option<String>,

    /// Spins up an asynchronous task that does the work.
    #[serde(rename = "use-task", skip_serializing_if = "Option::is_none")]
    pub use_task: Option<bool>,


}

impl AdminDatastoreCreatePruneRequest {
    pub fn new(backup_id: String, backup_type: models::PbsBackupTypeEnum) -> AdminDatastoreCreatePruneRequest {
        AdminDatastoreCreatePruneRequest {
            
            backup_id,
            
            backup_type,
            
            dry_run: None,
            
            keep_daily: None,
            
            keep_hourly: None,
            
            keep_last: None,
            
            keep_monthly: None,
            
            keep_weekly: None,
            
            keep_yearly: None,
            
            ns: None,
            
            use_task: None,
            
        }
    }
}


