/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AdminDatastoreGetDatastoreResponseDataInner {

    /// Datastore backend type
    #[serde(rename = "backend-type")]
    pub backend_type: models::PbsBackendTypeEnum,

    /// Comment.
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,

    /// If the datastore is in maintenance mode, information about it
    #[serde(rename = "maintenance", skip_serializing_if = "Option::is_none")]
    pub maintenance: Option<Box<models::PbsMaintenanceField>>,

    /// Current mounting status of a datastore, useful for removable datastores.
    #[serde(rename = "mount-status")]
    pub mount_status: models::PbsMountStatusEnum,

    /// Datastore name.
    #[serde(rename = "store")]
    pub store: String,


}

impl AdminDatastoreGetDatastoreResponseDataInner {
    pub fn new(backend_type: models::PbsBackendTypeEnum, mount_status: models::PbsMountStatusEnum, store: String) -> AdminDatastoreGetDatastoreResponseDataInner {
        AdminDatastoreGetDatastoreResponseDataInner {
            
            backend_type,
            
            comment: None,
            
            maintenance: None,
            
            mount_status,
            
            store,
            
        }
    }
}


