/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BackupUpgradeCreateFixedIndexRequest {

    /// Backup archive name.
    #[serde(rename = "archive-name")]
    pub archive_name: String,

    /// If set, compare last backup's csum and reuse index for incremental backup if it matches.
    #[serde(rename = "reuse-csum", skip_serializing_if = "Option::is_none")]
    pub reuse_csum: Option<String>,

    /// File size.
    #[serde(rename = "size", skip_serializing_if = "Option::is_none")]
    pub size: Option<i64>,


}

impl BackupUpgradeCreateFixedIndexRequest {
    pub fn new(archive_name: String) -> BackupUpgradeCreateFixedIndexRequest {
        BackupUpgradeCreateFixedIndexRequest {
            
            archive_name,
            
            reuse_csum: None,
            
            size: None,
            
        }
    }
}


