/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BackupUpgradeCreateBlobRequest {

    /// Encoded blob size.
    #[serde(rename = "encoded-size")]
    pub encoded_size: i32,

    /// Backup archive name.
    #[serde(rename = "file-name")]
    pub file_name: String,


}

impl BackupUpgradeCreateBlobRequest {
    pub fn new(encoded_size: i32, file_name: String) -> BackupUpgradeCreateBlobRequest {
        BackupUpgradeCreateBlobRequest {
            
            encoded_size,
            
            file_name,
            
        }
    }
}


