/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BackupUpgradeCreateDynamicChunkRequest {

    /// Chunk digest (SHA256).
    #[serde(rename = "digest")]
    pub digest: String,

    /// Encoded chunk size.
    #[serde(rename = "encoded-size")]
    pub encoded_size: i32,

    /// Chunk size.
    #[serde(rename = "size")]
    pub size: i32,

    /// Dynamic writer ID.
    #[serde(rename = "wid")]
    pub wid: i32,


}

impl BackupUpgradeCreateDynamicChunkRequest {
    pub fn new(digest: String, encoded_size: i32, size: i32, wid: i32) -> BackupUpgradeCreateDynamicChunkRequest {
        BackupUpgradeCreateDynamicChunkRequest {
            
            digest,
            
            encoded_size,
            
            size,
            
            wid,
            
        }
    }
}


