/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigPruneCreatePruneRequest {

    /// Comment.
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,

    /// Disable this job.
    #[serde(rename = "disable", skip_serializing_if = "Option::is_none")]
    pub disable: Option<bool>,

    /// Job ID.
    #[serde(rename = "id")]
    pub id: String,

    /// Number of daily backups to keep.
    #[serde(rename = "keep-daily", skip_serializing_if = "Option::is_none")]
    pub keep_daily: Option<i64>,

    /// Number of hourly backups to keep.
    #[serde(rename = "keep-hourly", skip_serializing_if = "Option::is_none")]
    pub keep_hourly: Option<i64>,

    /// Number of backups to keep.
    #[serde(rename = "keep-last", skip_serializing_if = "Option::is_none")]
    pub keep_last: Option<i64>,

    /// Number of monthly backups to keep.
    #[serde(rename = "keep-monthly", skip_serializing_if = "Option::is_none")]
    pub keep_monthly: Option<i64>,

    /// Number of weekly backups to keep.
    #[serde(rename = "keep-weekly", skip_serializing_if = "Option::is_none")]
    pub keep_weekly: Option<i64>,

    /// Number of yearly backups to keep.
    #[serde(rename = "keep-yearly", skip_serializing_if = "Option::is_none")]
    pub keep_yearly: Option<i64>,

    /// How many levels of namespaces should be operated on (0 == no recursion, empty == automatic full recursion, namespace depths reduce maximum allowed value)
    #[serde(rename = "max-depth", skip_serializing_if = "Option::is_none")]
    pub max_depth: Option<i32>,

    /// Namespace.
    #[serde(rename = "ns", skip_serializing_if = "Option::is_none")]
    pub ns: Option<String>,

    /// Run prune job at specified schedule.
    #[serde(rename = "schedule")]
    pub schedule: String,

    /// Datastore name.
    #[serde(rename = "store")]
    pub store: String,


}

impl ConfigPruneCreatePruneRequest {
    pub fn new(id: String, schedule: String, store: String) -> ConfigPruneCreatePruneRequest {
        ConfigPruneCreatePruneRequest {
            
            comment: None,
            
            disable: None,
            
            id,
            
            keep_daily: None,
            
            keep_hourly: None,
            
            keep_last: None,
            
            keep_monthly: None,
            
            keep_weekly: None,
            
            keep_yearly: None,
            
            max_depth: None,
            
            ns: None,
            
            schedule,
            
            store,
            
        }
    }
}


