/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigTapeEncryptionKeysCreateTapeEncryptionKeysRequest {

    /// Password hint.
    #[serde(rename = "hint", skip_serializing_if = "Option::is_none")]
    pub hint: Option<String>,

    /// Key derivation function for password protected encryption keys.
    #[serde(rename = "kdf", skip_serializing_if = "Option::is_none")]
    pub kdf: Option<models::PbsKdfEnum>,

    /// Restore/Re-create a key from this JSON string.
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,

    /// A secret password.
    #[serde(rename = "password")]
    pub password: String,


}

impl ConfigTapeEncryptionKeysCreateTapeEncryptionKeysRequest {
    pub fn new(password: String) -> ConfigTapeEncryptionKeysCreateTapeEncryptionKeysRequest {
        ConfigTapeEncryptionKeysCreateTapeEncryptionKeysRequest {
            
            hint: None,
            
            kdf: None,
            
            key: None,
            
            password,
            
        }
    }
}


