/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigNotificationsCreateWebhookRequest {

    /// The HTTP body to send. Supports templating.
    #[serde(rename = "body", skip_serializing_if = "Option::is_none")]
    pub body: Option<String>,

    /// Comment.
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,

    /// Disable this target.
    #[serde(rename = "disable", skip_serializing_if = "Option::is_none")]
    pub disable: Option<bool>,

    /// Array of HTTP headers. Each entry is a property string with a name and a value. The value property contains the header in base64 encoding. Supports templating.
    #[serde(rename = "header", skip_serializing_if = "Option::is_none")]
    pub header: Option<Vec<models::ConfigNotificationsGetWebhookResponseDataInnerHeaderInner>>,

    /// HTTP Method to use.
    #[serde(rename = "method")]
    pub method: models::PbsMethodEnum,

    /// Name schema for targets and matchers
    #[serde(rename = "name")]
    pub name: String,

    /// The origin of a notification configuration entry.
    #[serde(rename = "origin", skip_serializing_if = "Option::is_none")]
    pub origin: Option<models::PbsOriginEnum>,

    /// Array of secrets. Each entry is a property string with a name and an optional value. The value property contains the secret in base64 encoding. For any API endpoints returning the endpoint config, only the secret name but not the value will be returned. When updating the config, also send all secrets that you want to keep, setting only the name but not the value. Can be accessed from templates.
    #[serde(rename = "secret", skip_serializing_if = "Option::is_none")]
    pub secret: Option<Vec<models::ConfigNotificationsGetWebhookResponseDataInnerHeaderInner>>,

    /// HTTP(s) url with optional port.
    #[serde(rename = "url")]
    pub url: String,


}

impl ConfigNotificationsCreateWebhookRequest {
    pub fn new(method: models::PbsMethodEnum, name: String, url: String) -> ConfigNotificationsCreateWebhookRequest {
        ConfigNotificationsCreateWebhookRequest {
            
            body: None,
            
            comment: None,
            
            disable: None,
            
            header: None,
            
            method,
            
            name,
            
            origin: None,
            
            secret: None,
            
            url,
            
        }
    }
}


