/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigNotificationsUpdateGotifyRequest {

    /// Comment.
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,

    /// List of properties to delete.
    #[serde(rename = "delete", skip_serializing_if = "Option::is_none")]
    pub delete: Option<Vec<models::PbsConfigNotificationsInlineEnum>>,

    /// Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.
    #[serde(rename = "digest", skip_serializing_if = "Option::is_none")]
    pub digest: Option<String>,

    /// Disable this target.
    #[serde(rename = "disable", skip_serializing_if = "Option::is_none")]
    pub disable: Option<bool>,

    /// Gotify Server URL.
    #[serde(rename = "server", skip_serializing_if = "Option::is_none")]
    pub server: Option<String>,

    /// Authentication token
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,


}

impl ConfigNotificationsUpdateGotifyRequest {
    pub fn new() -> ConfigNotificationsUpdateGotifyRequest {
        ConfigNotificationsUpdateGotifyRequest {
            
            comment: None,
            
            delete: None,
            
            digest: None,
            
            disable: None,
            
            server: None,
            
            token: None,
            
        }
    }
}


