/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigTrafficControlUpdateTrafficControlRequest {

    /// Byte size with optional unit (B, KB (base 10), MB, GB, ..., KiB (base 2), MiB, Gib, ...).
    #[serde(rename = "burst-in", skip_serializing_if = "Option::is_none")]
    pub burst_in: Option<String>,

    /// Byte size with optional unit (B, KB (base 10), MB, GB, ..., KiB (base 2), MiB, Gib, ...).
    #[serde(rename = "burst-out", skip_serializing_if = "Option::is_none")]
    pub burst_out: Option<String>,

    /// Comment.
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,

    /// List of properties to delete.
    #[serde(rename = "delete", skip_serializing_if = "Option::is_none")]
    pub delete: Option<Vec<models::PbsConfigTrafficControlInlineEnum>>,

    /// Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.
    #[serde(rename = "digest", skip_serializing_if = "Option::is_none")]
    pub digest: Option<String>,

    /// Rule applies to Source IPs within this networks
    #[serde(rename = "network", skip_serializing_if = "Option::is_none")]
    pub network: Option<Vec<String>>,

    /// Byte size with optional unit (B, KB (base 10), MB, GB, ..., KiB (base 2), MiB, Gib, ...).
    #[serde(rename = "rate-in", skip_serializing_if = "Option::is_none")]
    pub rate_in: Option<String>,

    /// Byte size with optional unit (B, KB (base 10), MB, GB, ..., KiB (base 2), MiB, Gib, ...).
    #[serde(rename = "rate-out", skip_serializing_if = "Option::is_none")]
    pub rate_out: Option<String>,

    /// Enable the rule at specific times
    #[serde(rename = "timeframe", skip_serializing_if = "Option::is_none")]
    pub timeframe: Option<Vec<String>>,

    /// Rule applies to authenticated API requests of any of these users (overrides IP-only rules)
    #[serde(rename = "users", skip_serializing_if = "Option::is_none")]
    pub users: Option<Vec<String>>,


}

impl ConfigTrafficControlUpdateTrafficControlRequest {
    pub fn new() -> ConfigTrafficControlUpdateTrafficControlRequest {
        ConfigTrafficControlUpdateTrafficControlRequest {
            
            burst_in: None,
            
            burst_out: None,
            
            comment: None,
            
            delete: None,
            
            digest: None,
            
            network: None,
            
            rate_in: None,
            
            rate_out: None,
            
            timeframe: None,
            
            users: None,
            
        }
    }
}


