/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigMetricsUpdateInfluxdbUdpRequest {

    /// Comment.
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,

    /// List of properties to delete.
    #[serde(rename = "delete", skip_serializing_if = "Option::is_none")]
    pub delete: Option<Vec<models::PbsConfigMetricsInlineEnum2>>,

    /// Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.
    #[serde(rename = "digest", skip_serializing_if = "Option::is_none")]
    pub digest: Option<String>,

    /// Enables or disables the metrics server
    #[serde(rename = "enable", skip_serializing_if = "Option::is_none")]
    pub enable: Option<bool>,

    /// host:port combination (Host can be DNS name or IP address).
    #[serde(rename = "host", skip_serializing_if = "Option::is_none")]
    pub host: Option<String>,

    /// The MTU
    #[serde(rename = "mtu", skip_serializing_if = "Option::is_none")]
    pub mtu: Option<i64>,


}

impl ConfigMetricsUpdateInfluxdbUdpRequest {
    pub fn new() -> ConfigMetricsUpdateInfluxdbUdpRequest {
        ConfigMetricsUpdateInfluxdbUdpRequest {
            
            comment: None,
            
            delete: None,
            
            digest: None,
            
            enable: None,
            
            host: None,
            
            mtu: None,
            
        }
    }
}


