/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigNotificationsUpdateSendmailRequest {

    /// Author of the mail. Defaults to 'Proxmox Backup Server ($hostname)'
    #[serde(rename = "author", skip_serializing_if = "Option::is_none")]
    pub author: Option<String>,

    /// Comment.
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,

    /// List of properties to delete.
    #[serde(rename = "delete", skip_serializing_if = "Option::is_none")]
    pub delete: Option<Vec<models::PbsConfigNotificationsInlineEnum2>>,

    /// Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.
    #[serde(rename = "digest", skip_serializing_if = "Option::is_none")]
    pub digest: Option<String>,

    /// Disable this target.
    #[serde(rename = "disable", skip_serializing_if = "Option::is_none")]
    pub disable: Option<bool>,

    /// `From` address for sent E-Mails. If the parameter is not set, the plugin will fall back to the email-from setting from node.cfg (PBS). If that is also not set, the plugin will default to root@$hostname, where $hostname is the hostname of the node.
    #[serde(rename = "from-address", skip_serializing_if = "Option::is_none")]
    pub from_address: Option<String>,

    /// Mail address to send a mail to.
    #[serde(rename = "mailto", skip_serializing_if = "Option::is_none")]
    pub mailto: Option<Vec<String>>,

    /// Users to send a mail to. The email address of the user will be looked up in users.cfg.
    #[serde(rename = "mailto-user", skip_serializing_if = "Option::is_none")]
    pub mailto_user: Option<Vec<String>>,


}

impl ConfigNotificationsUpdateSendmailRequest {
    pub fn new() -> ConfigNotificationsUpdateSendmailRequest {
        ConfigNotificationsUpdateSendmailRequest {
            
            author: None,
            
            comment: None,
            
            delete: None,
            
            digest: None,
            
            disable: None,
            
            from_address: None,
            
            mailto: None,
            
            mailto_user: None,
            
        }
    }
}


