/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigNotificationsUpdateSmtpRequest {

    /// Author of the mail. Defaults to 'Proxmox Backup Server ($hostname)'
    #[serde(rename = "author", skip_serializing_if = "Option::is_none")]
    pub author: Option<String>,

    /// Comment.
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,

    /// List of properties to delete.
    #[serde(rename = "delete", skip_serializing_if = "Option::is_none")]
    pub delete: Option<Vec<models::PbsConfigNotificationsInlineEnum3>>,

    /// Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.
    #[serde(rename = "digest", skip_serializing_if = "Option::is_none")]
    pub digest: Option<String>,

    /// Disable this target.
    #[serde(rename = "disable", skip_serializing_if = "Option::is_none")]
    pub disable: Option<bool>,

    /// `From` address for the mail. SMTP relays might require that this address is owned by the user in order to avoid spoofing. The `From` header in the email will be set to `$author <$from-address>`.
    #[serde(rename = "from-address", skip_serializing_if = "Option::is_none")]
    pub from_address: Option<String>,

    /// Mail address to send a mail to.
    #[serde(rename = "mailto", skip_serializing_if = "Option::is_none")]
    pub mailto: Option<Vec<String>>,

    /// Users to send a mail to. The email address of the user will be looked up in users.cfg.
    #[serde(rename = "mailto-user", skip_serializing_if = "Option::is_none")]
    pub mailto_user: Option<Vec<String>>,

    /// Connection security
    #[serde(rename = "mode", skip_serializing_if = "Option::is_none")]
    pub mode: Option<models::PbsConfigNotificationsModeEnum>,

    /// SMTP authentication password
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,

    /// The port to connect to. If not set, the used port defaults to 25 (insecure), 465 (tls) or 587 (starttls), depending on the value of mode
    #[serde(rename = "port", skip_serializing_if = "Option::is_none")]
    pub port: Option<i32>,

    /// Host name or IP of the SMTP relay.
    #[serde(rename = "server", skip_serializing_if = "Option::is_none")]
    pub server: Option<String>,

    /// Username to use during authentication. If no username is set, no authentication will be performed. The PLAIN and LOGIN authentication methods are supported
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,


}

impl ConfigNotificationsUpdateSmtpRequest {
    pub fn new() -> ConfigNotificationsUpdateSmtpRequest {
        ConfigNotificationsUpdateSmtpRequest {
            
            author: None,
            
            comment: None,
            
            delete: None,
            
            digest: None,
            
            disable: None,
            
            from_address: None,
            
            mailto: None,
            
            mailto_user: None,
            
            mode: None,
            
            password: None,
            
            port: None,
            
            server: None,
            
            username: None,
            
        }
    }
}


