/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigAccessGetPamResponseData {

    /// Comment.
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,

    /// True if you want this to be the default realm selected on login.
    #[serde(rename = "default", skip_serializing_if = "Option::is_none")]
    pub default: Option<bool>,

    /// Realm name.
    #[serde(rename = "realm")]
    pub realm: String,

    /// type of the realm
    #[serde(rename = "type")]
    pub r#type: models::PbsTypeEnum,


}

impl ConfigAccessGetPamResponseData {
    pub fn new(realm: String, r#type: models::PbsTypeEnum) -> ConfigAccessGetPamResponseData {
        ConfigAccessGetPamResponseData {
            
            comment: None,
            
            default: None,
            
            realm,
            
            r#type,
            
        }
    }
}


