/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigDriveGetDriveResponseDataInner {

    /// Tape Changer Identifier.
    #[serde(rename = "changer", skip_serializing_if = "Option::is_none")]
    pub changer: Option<String>,

    /// Associated changer drive number (requires option changer)
    #[serde(rename = "changer-drivenum", skip_serializing_if = "Option::is_none")]
    pub changer_drivenum: Option<i32>,

    /// Drive Identifier.
    #[serde(rename = "name")]
    pub name: String,

    /// The path to a LTO SCSI-generic tape device (i.e. '/dev/sg0')
    #[serde(rename = "path")]
    pub path: String,


}

impl ConfigDriveGetDriveResponseDataInner {
    pub fn new(name: String, path: String) -> ConfigDriveGetDriveResponseDataInner {
        ConfigDriveGetDriveResponseDataInner {
            
            changer: None,
            
            changer_drivenum: None,
            
            name,
            
            path,
            
        }
    }
}


