/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigTapeEncryptionKeysUpdateTapeEncryptionKeysRequest {

    /// Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.
    #[serde(rename = "digest", skip_serializing_if = "Option::is_none")]
    pub digest: Option<String>,

    /// Reset the passphrase for a tape key, using the root-only accessible copy.
    #[serde(rename = "force", skip_serializing_if = "Option::is_none")]
    pub force: Option<bool>,

    /// Password hint.
    #[serde(rename = "hint")]
    pub hint: String,

    /// Key derivation function for password protected encryption keys.
    #[serde(rename = "kdf", skip_serializing_if = "Option::is_none")]
    pub kdf: Option<models::PbsKdfEnum>,

    /// The new password.
    #[serde(rename = "new-password")]
    pub new_password: String,

    /// The current password.
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,


}

impl ConfigTapeEncryptionKeysUpdateTapeEncryptionKeysRequest {
    pub fn new(hint: String, new_password: String) -> ConfigTapeEncryptionKeysUpdateTapeEncryptionKeysRequest {
        ConfigTapeEncryptionKeysUpdateTapeEncryptionKeysRequest {
            
            digest: None,
            
            force: None,
            
            hint,
            
            kdf: None,
            
            new_password,
            
            password: None,
            
        }
    }
}


