/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigNotificationsGetGotifyResponseDataInner {

    /// Comment.
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,

    /// Disable this target.
    #[serde(rename = "disable", skip_serializing_if = "Option::is_none")]
    pub disable: Option<bool>,

    /// Deprecated.
    #[serde(rename = "filter", skip_serializing_if = "Option::is_none")]
    pub filter: Option<String>,

    /// Name schema for targets and matchers
    #[serde(rename = "name")]
    pub name: String,

    /// The origin of a notification configuration entry.
    #[serde(rename = "origin", skip_serializing_if = "Option::is_none")]
    pub origin: Option<models::PbsOriginEnum>,

    /// Gotify Server URL.
    #[serde(rename = "server")]
    pub server: String,


}

impl ConfigNotificationsGetGotifyResponseDataInner {
    pub fn new(name: String, server: String) -> ConfigNotificationsGetGotifyResponseDataInner {
        ConfigNotificationsGetGotifyResponseDataInner {
            
            comment: None,
            
            disable: None,
            
            filter: None,
            
            name,
            
            origin: None,
            
            server,
            
        }
    }
}


