/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigNotificationsGetSendmailResponseDataInner {

    /// Author of the mail. Defaults to 'Proxmox Backup Server ($hostname)'
    #[serde(rename = "author", skip_serializing_if = "Option::is_none")]
    pub author: Option<String>,

    /// Comment.
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,

    /// Disable this target.
    #[serde(rename = "disable", skip_serializing_if = "Option::is_none")]
    pub disable: Option<bool>,

    /// Deprecated.
    #[serde(rename = "filter", skip_serializing_if = "Option::is_none")]
    pub filter: Option<String>,

    /// `From` address for sent E-Mails. If the parameter is not set, the plugin will fall back to the email-from setting from node.cfg (PBS). If that is also not set, the plugin will default to root@$hostname, where $hostname is the hostname of the node.
    #[serde(rename = "from-address", skip_serializing_if = "Option::is_none")]
    pub from_address: Option<String>,

    /// Mail address to send a mail to.
    #[serde(rename = "mailto", skip_serializing_if = "Option::is_none")]
    pub mailto: Option<Vec<String>>,

    /// Users to send a mail to. The email address of the user will be looked up in users.cfg.
    #[serde(rename = "mailto-user", skip_serializing_if = "Option::is_none")]
    pub mailto_user: Option<Vec<String>>,

    /// Name schema for targets and matchers
    #[serde(rename = "name")]
    pub name: String,

    /// The origin of a notification configuration entry.
    #[serde(rename = "origin", skip_serializing_if = "Option::is_none")]
    pub origin: Option<models::PbsOriginEnum>,


}

impl ConfigNotificationsGetSendmailResponseDataInner {
    pub fn new(name: String) -> ConfigNotificationsGetSendmailResponseDataInner {
        ConfigNotificationsGetSendmailResponseDataInner {
            
            author: None,
            
            comment: None,
            
            disable: None,
            
            filter: None,
            
            from_address: None,
            
            mailto: None,
            
            mailto_user: None,
            
            name,
            
            origin: None,
            
        }
    }
}


