/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigNotificationsGetMatcherFieldValuesResponseDataInner {

    /// Additional comment for this value.
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,

    /// Field this value belongs to.
    #[serde(rename = "field")]
    pub field: String,

    /// Notification metadata value known by the system.
    #[serde(rename = "value")]
    pub value: String,


}

impl ConfigNotificationsGetMatcherFieldValuesResponseDataInner {
    pub fn new(field: String, value: String) -> ConfigNotificationsGetMatcherFieldValuesResponseDataInner {
        ConfigNotificationsGetMatcherFieldValuesResponseDataInner {
            
            comment: None,
            
            field,
            
            value,
            
        }
    }
}


