/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigEncryptionKeysCreateConfigEncryptionKeysByIdRequest {

    /// Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.
    #[serde(rename = "digest", skip_serializing_if = "Option::is_none")]
    pub digest: Option<String>,


}

impl ConfigEncryptionKeysCreateConfigEncryptionKeysByIdRequest {
    pub fn new() -> ConfigEncryptionKeysCreateConfigEncryptionKeysByIdRequest {
        ConfigEncryptionKeysCreateConfigEncryptionKeysByIdRequest {
            
            digest: None,
            
        }
    }
}


