/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigMetricsGetInfluxdbUdpResponseDataInner {

    /// Comment.
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,

    /// Enables or disables the metrics server
    #[serde(rename = "enable", skip_serializing_if = "Option::is_none")]
    pub enable: Option<bool>,

    /// host:port combination (Host can be DNS name or IP address).
    #[serde(rename = "host")]
    pub host: String,

    /// The MTU
    #[serde(rename = "mtu", skip_serializing_if = "Option::is_none")]
    pub mtu: Option<i64>,

    /// Metrics Server ID.
    #[serde(rename = "name")]
    pub name: String,


}

impl ConfigMetricsGetInfluxdbUdpResponseDataInner {
    pub fn new(host: String, name: String) -> ConfigMetricsGetInfluxdbUdpResponseDataInner {
        ConfigMetricsGetInfluxdbUdpResponseDataInner {
            
            comment: None,
            
            enable: None,
            
            host,
            
            mtu: None,
            
            name,
            
        }
    }
}


