/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodesDisksGetZfsResponseDataInner {

    /// Used size
    #[serde(rename = "alloc")]
    pub alloc: i64,

    /// ZFS deduplication ratio
    #[serde(rename = "dedup")]
    pub dedup: f64,

    /// ZFS fragnentation level
    #[serde(rename = "frag")]
    pub frag: i64,

    /// Free space
    #[serde(rename = "free")]
    pub free: i64,

    /// Health
    #[serde(rename = "health")]
    pub health: String,

    /// zpool name
    #[serde(rename = "name")]
    pub name: String,

    /// Total size
    #[serde(rename = "size")]
    pub size: i64,


}

impl NodesDisksGetZfsResponseDataInner {
    pub fn new(alloc: i64, dedup: f64, frag: i64, free: i64, health: String, name: String, size: i64) -> NodesDisksGetZfsResponseDataInner {
        NodesDisksGetZfsResponseDataInner {
            
            alloc,
            
            dedup,
            
            frag,
            
            free,
            
            health,
            
            name,
            
            size,
            
        }
    }
}


