/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodesDisksCreateDirectoryRequest {

    /// Configure a datastore using the directory.
    #[serde(rename = "add-datastore", skip_serializing_if = "Option::is_none")]
    pub add_datastore: Option<bool>,

    /// Block device name (/sys/block/<name>).
    #[serde(rename = "disk")]
    pub disk: String,

    /// A file system type supported by our tooling.
    #[serde(rename = "filesystem", skip_serializing_if = "Option::is_none")]
    pub filesystem: Option<models::PbsFilesystemEnum>,

    /// Datastore name.
    #[serde(rename = "name")]
    pub name: String,

    /// The added datastore is removable.
    #[serde(rename = "removable-datastore", skip_serializing_if = "Option::is_none")]
    pub removable_datastore: Option<bool>,


}

impl NodesDisksCreateDirectoryRequest {
    pub fn new(disk: String, name: String) -> NodesDisksCreateDirectoryRequest {
        NodesDisksCreateDirectoryRequest {
            
            add_datastore: None,
            
            disk,
            
            filesystem: None,
            
            name,
            
            removable_datastore: None,
            
        }
    }
}


