/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodesConfigGetConfigResponseData {

    /// The acme account to use on this node.
    #[serde(rename = "acme", skip_serializing_if = "Option::is_none")]
    pub acme: Option<Box<models::PbsAcmeField>>,

    /// ACME domain configuration string
    #[serde(rename = "acmedomain0", skip_serializing_if = "Option::is_none")]
    pub acmedomain0: Option<Box<models::PbsAcmedomainField>>,

    /// ACME domain configuration string
    #[serde(rename = "acmedomain1", skip_serializing_if = "Option::is_none")]
    pub acmedomain1: Option<Box<models::PbsAcmedomainField>>,

    /// ACME domain configuration string
    #[serde(rename = "acmedomain2", skip_serializing_if = "Option::is_none")]
    pub acmedomain2: Option<Box<models::PbsAcmedomainField>>,

    /// ACME domain configuration string
    #[serde(rename = "acmedomain3", skip_serializing_if = "Option::is_none")]
    pub acmedomain3: Option<Box<models::PbsAcmedomainField>>,

    /// ACME domain configuration string
    #[serde(rename = "acmedomain4", skip_serializing_if = "Option::is_none")]
    pub acmedomain4: Option<Box<models::PbsAcmedomainField>>,

    /// OpenSSL cipher list used by the proxy for TLS <= 1.2
    #[serde(rename = "ciphers-tls-1.2", skip_serializing_if = "Option::is_none")]
    pub ciphers_tls_1_2: Option<String>,

    /// OpenSSL ciphersuites list used by the proxy for TLS 1.3
    #[serde(rename = "ciphers-tls-1.3", skip_serializing_if = "Option::is_none")]
    pub ciphers_tls_1_3: Option<String>,

    /// Consent banner text
    #[serde(rename = "consent-text", skip_serializing_if = "Option::is_none")]
    pub consent_text: Option<String>,

    /// All available languages in Proxmox. Taken from proxmox-i18n repository. pt_BR, zh_CN, and zh_TW use the same case in the translation files.
    #[serde(rename = "default-lang", skip_serializing_if = "Option::is_none")]
    pub default_lang: Option<models::PbsDefaultLangEnum>,

    /// Comment (multiple lines).
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,

    /// E-Mail Address.
    #[serde(rename = "email-from", skip_serializing_if = "Option::is_none")]
    pub email_from: Option<String>,

    /// HTTP proxy configuration [http://]<host>[:port]
    #[serde(rename = "http-proxy", skip_serializing_if = "Option::is_none")]
    pub http_proxy: Option<String>,

    /// Maximum days to keep Task logs
    #[serde(rename = "task-log-max-days", skip_serializing_if = "Option::is_none")]
    pub task_log_max_days: Option<i64>,


}

impl NodesConfigGetConfigResponseData {
    pub fn new() -> NodesConfigGetConfigResponseData {
        NodesConfigGetConfigResponseData {
            
            acme: None,
            
            acmedomain0: None,
            
            acmedomain1: None,
            
            acmedomain2: None,
            
            acmedomain3: None,
            
            acmedomain4: None,
            
            ciphers_tls_1_2: None,
            
            ciphers_tls_1_3: None,
            
            consent_text: None,
            
            default_lang: None,
            
            description: None,
            
            email_from: None,
            
            http_proxy: None,
            
            task_log_max_days: None,
            
        }
    }
}


