/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodesDisksCreateInitgptRequest {

    /// Block device name (/sys/block/<name>).
    #[serde(rename = "disk")]
    pub disk: String,

    /// UUID for the GPT table.
    #[serde(rename = "uuid", skip_serializing_if = "Option::is_none")]
    pub uuid: Option<String>,


}

impl NodesDisksCreateInitgptRequest {
    pub fn new(disk: String) -> NodesDisksCreateInitgptRequest {
        NodesDisksCreateInitgptRequest {
            
            disk,
            
            uuid: None,
            
        }
    }
}


