/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodesDisksGetDirectoryResponseDataInner {

    /// The mounted device.
    #[serde(rename = "device")]
    pub device: String,

    /// A file system type supported by our tooling.
    #[serde(rename = "filesystem", skip_serializing_if = "Option::is_none")]
    pub filesystem: Option<models::PbsFilesystemEnum>,

    /// The name of the mount
    #[serde(rename = "name")]
    pub name: String,

    /// Mount options
    #[serde(rename = "options", skip_serializing_if = "Option::is_none")]
    pub options: Option<String>,

    /// The mount path.
    #[serde(rename = "path")]
    pub path: String,

    /// This is removable
    #[serde(rename = "removable")]
    pub removable: bool,

    /// The path of the mount unit.
    #[serde(rename = "unitfile")]
    pub unitfile: String,


}

impl NodesDisksGetDirectoryResponseDataInner {
    pub fn new(device: String, name: String, path: String, removable: bool, unitfile: String) -> NodesDisksGetDirectoryResponseDataInner {
        NodesDisksGetDirectoryResponseDataInner {
            
            device,
            
            filesystem: None,
            
            name,
            
            options: None,
            
            path,
            
            removable,
            
            unitfile,
            
        }
    }
}


