/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodesCreateTermproxyRequest {

    /// The command to run.
    #[serde(rename = "cmd", skip_serializing_if = "Option::is_none")]
    pub cmd: Option<models::PbsNodesCmdEnum>,


}

impl NodesCreateTermproxyRequest {
    pub fn new() -> NodesCreateTermproxyRequest {
        NodesCreateTermproxyRequest {
            
            cmd: None,
            
        }
    }
}


