/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodesAptGetRepositoriesResponseDataFilesInnerRepositoriesInner {

    /// Associated comment.
    #[serde(rename = "Comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,

    /// List of repository components.
    #[serde(rename = "Components")]
    pub components: Vec<String>,

    /// Whether the repository is enabled or not.
    #[serde(rename = "Enabled")]
    pub enabled: bool,

    /// The type of format used for an APT repository.
    #[serde(rename = "FileType")]
    pub file_type: models::PbsFileTypeEnum,

    /// Additional options.
    #[serde(rename = "Options", skip_serializing_if = "Option::is_none")]
    pub options: Option<Vec<models::NodesAptGetRepositoriesResponseDataFilesInnerRepositoriesInnerOptionsInner>>,

    /// List of distributions.
    #[serde(rename = "Suites")]
    pub suites: Vec<String>,

    /// List of package types.
    #[serde(rename = "Types")]
    pub types: Vec<models::PbsNodesAptInlineEnum>,

    /// List of repository URIs.
    #[serde(rename = "URIs")]
    pub uris: Vec<String>,


}

impl NodesAptGetRepositoriesResponseDataFilesInnerRepositoriesInner {
    pub fn new(components: Vec<String>, enabled: bool, file_type: models::PbsFileTypeEnum, suites: Vec<String>, types: Vec<models::PbsNodesAptInlineEnum>, uris: Vec<String>) -> NodesAptGetRepositoriesResponseDataFilesInnerRepositoriesInner {
        NodesAptGetRepositoriesResponseDataFilesInnerRepositoriesInner {
            
            comment: None,
            
            components,
            
            enabled,
            
            file_type,
            
            options: None,
            
            suites,
            
            types,
            
            uris,
            
        }
    }
}


