/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodesDisksGetListResponseDataInnerPartitionsInner {

    /// The partition devpath
    #[serde(rename = "devpath", skip_serializing_if = "Option::is_none")]
    pub devpath: Option<String>,

    /// The filesystem of the partition
    #[serde(rename = "filesystem", skip_serializing_if = "Option::is_none")]
    pub filesystem: Option<String>,

    /// GPT partition
    #[serde(rename = "gpt")]
    pub gpt: bool,

    /// Is the partition mounted
    #[serde(rename = "mounted")]
    pub mounted: bool,

    /// The partition name
    #[serde(rename = "name")]
    pub name: String,

    /// Size in bytes
    #[serde(rename = "size", skip_serializing_if = "Option::is_none")]
    pub size: Option<i64>,

    /// What a block device partition is used for.
    #[serde(rename = "used")]
    pub used: models::PbsNodesDisksUsedEnum,

    /// UUID
    #[serde(rename = "uuid", skip_serializing_if = "Option::is_none")]
    pub uuid: Option<String>,


}

impl NodesDisksGetListResponseDataInnerPartitionsInner {
    pub fn new(gpt: bool, mounted: bool, name: String, used: models::PbsNodesDisksUsedEnum) -> NodesDisksGetListResponseDataInnerPartitionsInner {
        NodesDisksGetListResponseDataInnerPartitionsInner {
            
            devpath: None,
            
            filesystem: None,
            
            gpt,
            
            mounted,
            
            name,
            
            size: None,
            
            used,
            
            uuid: None,
            
        }
    }
}


