/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PbsOriginEnum {
    #[serde(rename = "user-created")]
    UserCreated,
    #[serde(rename = "builtin")]
    Builtin,
    #[serde(rename = "modified-builtin")]
    ModifiedBuiltin,

}

impl std::fmt::Display for PbsOriginEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::UserCreated => write!(f, "user-created"),
            Self::Builtin => write!(f, "builtin"),
            Self::ModifiedBuiltin => write!(f, "modified-builtin"),
        }
    }
}

impl Default for PbsOriginEnum {
    fn default() -> PbsOriginEnum {
        Self::UserCreated
    }
}

