/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PbsAcrValuesField {
    PbsAcrValuesConfig(Box<models::PbsAcrValuesConfig>),
    String(String),
}

impl Default for PbsAcrValuesField {
    fn default() -> Self {
        Self::PbsAcrValuesConfig(Default::default())
    }
}

