/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PbsBackupTypeEnum {
    #[serde(rename = "vm")]
    Vm,
    #[serde(rename = "ct")]
    Ct,
    #[serde(rename = "host")]
    Host,

}

impl std::fmt::Display for PbsBackupTypeEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Vm => write!(f, "vm"),
            Self::Ct => write!(f, "ct"),
            Self::Host => write!(f, "host"),
        }
    }
}

impl Default for PbsBackupTypeEnum {
    fn default() -> PbsBackupTypeEnum {
        Self::Vm
    }
}

