/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PbsConfigMediaPoolInlineEnum {
    #[serde(rename = "allocation")]
    Allocation,
    #[serde(rename = "retention")]
    Retention,
    #[serde(rename = "template")]
    Template,
    #[serde(rename = "encrypt")]
    Encrypt,
    #[serde(rename = "comment")]
    Comment,

}

impl std::fmt::Display for PbsConfigMediaPoolInlineEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Allocation => write!(f, "allocation"),
            Self::Retention => write!(f, "retention"),
            Self::Template => write!(f, "template"),
            Self::Encrypt => write!(f, "encrypt"),
            Self::Comment => write!(f, "comment"),
        }
    }
}

impl Default for PbsConfigMediaPoolInlineEnum {
    fn default() -> PbsConfigMediaPoolInlineEnum {
        Self::Allocation
    }
}

