/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PbsNodesConfigInlineEnum {
    #[serde(rename = "acme")]
    Acme,
    #[serde(rename = "acmedomain0")]
    Acmedomain0,
    #[serde(rename = "acmedomain1")]
    Acmedomain1,
    #[serde(rename = "acmedomain2")]
    Acmedomain2,
    #[serde(rename = "acmedomain3")]
    Acmedomain3,
    #[serde(rename = "acmedomain4")]
    Acmedomain4,
    #[serde(rename = "http-proxy")]
    HttpProxy,
    #[serde(rename = "email-from")]
    EmailFrom,
    #[serde(rename = "ciphers-tls-1.3")]
    CiphersTls13,
    #[serde(rename = "ciphers-tls-1.2")]
    CiphersTls12,
    #[serde(rename = "default-lang")]
    DefaultLang,
    #[serde(rename = "description")]
    Description,
    #[serde(rename = "task-log-max-days")]
    TaskLogMaxDays,
    #[serde(rename = "consent-text")]
    ConsentText,

}

impl std::fmt::Display for PbsNodesConfigInlineEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Acme => write!(f, "acme"),
            Self::Acmedomain0 => write!(f, "acmedomain0"),
            Self::Acmedomain1 => write!(f, "acmedomain1"),
            Self::Acmedomain2 => write!(f, "acmedomain2"),
            Self::Acmedomain3 => write!(f, "acmedomain3"),
            Self::Acmedomain4 => write!(f, "acmedomain4"),
            Self::HttpProxy => write!(f, "http-proxy"),
            Self::EmailFrom => write!(f, "email-from"),
            Self::CiphersTls13 => write!(f, "ciphers-tls-1.3"),
            Self::CiphersTls12 => write!(f, "ciphers-tls-1.2"),
            Self::DefaultLang => write!(f, "default-lang"),
            Self::Description => write!(f, "description"),
            Self::TaskLogMaxDays => write!(f, "task-log-max-days"),
            Self::ConsentText => write!(f, "consent-text"),
        }
    }
}

impl Default for PbsNodesConfigInlineEnum {
    fn default() -> PbsNodesConfigInlineEnum {
        Self::Acme
    }
}

