/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PbsConfigNotificationsInlineEnum3 {
    #[serde(rename = "author")]
    Author,
    #[serde(rename = "comment")]
    Comment,
    #[serde(rename = "disable")]
    Disable,
    #[serde(rename = "mailto")]
    Mailto,
    #[serde(rename = "mailto-user")]
    MailtoUser,
    #[serde(rename = "password")]
    Password,
    #[serde(rename = "port")]
    Port,
    #[serde(rename = "username")]
    Username,

}

impl std::fmt::Display for PbsConfigNotificationsInlineEnum3 {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Author => write!(f, "author"),
            Self::Comment => write!(f, "comment"),
            Self::Disable => write!(f, "disable"),
            Self::Mailto => write!(f, "mailto"),
            Self::MailtoUser => write!(f, "mailto-user"),
            Self::Password => write!(f, "password"),
            Self::Port => write!(f, "port"),
            Self::Username => write!(f, "username"),
        }
    }
}

impl Default for PbsConfigNotificationsInlineEnum3 {
    fn default() -> PbsConfigNotificationsInlineEnum3 {
        Self::Author
    }
}

