/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PbsConfigMetricsInlineEnum2 {
    #[serde(rename = "enable")]
    Enable,
    #[serde(rename = "mtu")]
    Mtu,
    #[serde(rename = "comment")]
    Comment,

}

impl std::fmt::Display for PbsConfigMetricsInlineEnum2 {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Enable => write!(f, "enable"),
            Self::Mtu => write!(f, "mtu"),
            Self::Comment => write!(f, "comment"),
        }
    }
}

impl Default for PbsConfigMetricsInlineEnum2 {
    fn default() -> PbsConfigMetricsInlineEnum2 {
        Self::Enable
    }
}

