/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PbsTypeEnum {
    #[serde(rename = "pam")]
    Pam,
    #[serde(rename = "pbs")]
    Pbs,
    #[serde(rename = "openid")]
    Openid,
    #[serde(rename = "ldap")]
    Ldap,
    #[serde(rename = "ad")]
    Ad,

}

impl std::fmt::Display for PbsTypeEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Pam => write!(f, "pam"),
            Self::Pbs => write!(f, "pbs"),
            Self::Openid => write!(f, "openid"),
            Self::Ldap => write!(f, "ldap"),
            Self::Ad => write!(f, "ad"),
        }
    }
}

impl Default for PbsTypeEnum {
    fn default() -> PbsTypeEnum {
        Self::Pam
    }
}

