/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PbsConfigDatastoreInlineEnum {
    #[serde(rename = "comment")]
    Comment,
    #[serde(rename = "gc-schedule")]
    GcSchedule,
    #[serde(rename = "gc-on-unmount")]
    GcOnUnmount,
    #[serde(rename = "prune-schedule")]
    PruneSchedule,
    #[serde(rename = "keep-last")]
    KeepLast,
    #[serde(rename = "keep-hourly")]
    KeepHourly,
    #[serde(rename = "keep-daily")]
    KeepDaily,
    #[serde(rename = "keep-weekly")]
    KeepWeekly,
    #[serde(rename = "keep-monthly")]
    KeepMonthly,
    #[serde(rename = "keep-yearly")]
    KeepYearly,
    #[serde(rename = "verify-new")]
    VerifyNew,
    #[serde(rename = "notify-user")]
    NotifyUser,
    #[serde(rename = "notify")]
    Notify,
    #[serde(rename = "notification-mode")]
    NotificationMode,
    #[serde(rename = "tuning")]
    Tuning,
    #[serde(rename = "maintenance-mode")]
    MaintenanceMode,
    #[serde(rename = "notification-thresholds")]
    NotificationThresholds,
    #[serde(rename = "counter-reset-schedule")]
    CounterResetSchedule,

}

impl std::fmt::Display for PbsConfigDatastoreInlineEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Comment => write!(f, "comment"),
            Self::GcSchedule => write!(f, "gc-schedule"),
            Self::GcOnUnmount => write!(f, "gc-on-unmount"),
            Self::PruneSchedule => write!(f, "prune-schedule"),
            Self::KeepLast => write!(f, "keep-last"),
            Self::KeepHourly => write!(f, "keep-hourly"),
            Self::KeepDaily => write!(f, "keep-daily"),
            Self::KeepWeekly => write!(f, "keep-weekly"),
            Self::KeepMonthly => write!(f, "keep-monthly"),
            Self::KeepYearly => write!(f, "keep-yearly"),
            Self::VerifyNew => write!(f, "verify-new"),
            Self::NotifyUser => write!(f, "notify-user"),
            Self::Notify => write!(f, "notify"),
            Self::NotificationMode => write!(f, "notification-mode"),
            Self::Tuning => write!(f, "tuning"),
            Self::MaintenanceMode => write!(f, "maintenance-mode"),
            Self::NotificationThresholds => write!(f, "notification-thresholds"),
            Self::CounterResetSchedule => write!(f, "counter-reset-schedule"),
        }
    }
}

impl Default for PbsConfigDatastoreInlineEnum {
    fn default() -> PbsConfigDatastoreInlineEnum {
        Self::Comment
    }
}

