/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PbsConfigSyncInlineEnum {
    #[serde(rename = "remote")]
    Remote,
    #[serde(rename = "owner")]
    Owner,
    #[serde(rename = "comment")]
    Comment,
    #[serde(rename = "schedule")]
    Schedule,
    #[serde(rename = "remove-vanished")]
    RemoveVanished,
    #[serde(rename = "group-filter")]
    GroupFilter,
    #[serde(rename = "rate-in")]
    RateIn,
    #[serde(rename = "burst-in")]
    BurstIn,
    #[serde(rename = "rate-out")]
    RateOut,
    #[serde(rename = "burst-out")]
    BurstOut,
    #[serde(rename = "ns")]
    Ns,
    #[serde(rename = "remote-ns")]
    RemoteNs,
    #[serde(rename = "max-depth")]
    MaxDepth,
    #[serde(rename = "transfer-last")]
    TransferLast,
    #[serde(rename = "encrypted-only")]
    EncryptedOnly,
    #[serde(rename = "verified-only")]
    VerifiedOnly,
    #[serde(rename = "run-on-mount")]
    RunOnMount,
    #[serde(rename = "unmount-on-done")]
    UnmountOnDone,
    #[serde(rename = "sync-direction")]
    SyncDirection,
    #[serde(rename = "worker-threads")]
    WorkerThreads,
    #[serde(rename = "active-encryption-key")]
    ActiveEncryptionKey,
    #[serde(rename = "associated-key")]
    AssociatedKey,

}

impl std::fmt::Display for PbsConfigSyncInlineEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Remote => write!(f, "remote"),
            Self::Owner => write!(f, "owner"),
            Self::Comment => write!(f, "comment"),
            Self::Schedule => write!(f, "schedule"),
            Self::RemoveVanished => write!(f, "remove-vanished"),
            Self::GroupFilter => write!(f, "group-filter"),
            Self::RateIn => write!(f, "rate-in"),
            Self::BurstIn => write!(f, "burst-in"),
            Self::RateOut => write!(f, "rate-out"),
            Self::BurstOut => write!(f, "burst-out"),
            Self::Ns => write!(f, "ns"),
            Self::RemoteNs => write!(f, "remote-ns"),
            Self::MaxDepth => write!(f, "max-depth"),
            Self::TransferLast => write!(f, "transfer-last"),
            Self::EncryptedOnly => write!(f, "encrypted-only"),
            Self::VerifiedOnly => write!(f, "verified-only"),
            Self::RunOnMount => write!(f, "run-on-mount"),
            Self::UnmountOnDone => write!(f, "unmount-on-done"),
            Self::SyncDirection => write!(f, "sync-direction"),
            Self::WorkerThreads => write!(f, "worker-threads"),
            Self::ActiveEncryptionKey => write!(f, "active-encryption-key"),
            Self::AssociatedKey => write!(f, "associated-key"),
        }
    }
}

impl Default for PbsConfigSyncInlineEnum {
    fn default() -> PbsConfigSyncInlineEnum {
        Self::Remote
    }
}

