/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PbsConfigPruneInlineEnum {
    #[serde(rename = "comment")]
    Comment,
    #[serde(rename = "disable")]
    Disable,
    #[serde(rename = "ns")]
    Ns,
    #[serde(rename = "max-depth")]
    MaxDepth,
    #[serde(rename = "keep-last")]
    KeepLast,
    #[serde(rename = "keep-hourly")]
    KeepHourly,
    #[serde(rename = "keep-daily")]
    KeepDaily,
    #[serde(rename = "keep-weekly")]
    KeepWeekly,
    #[serde(rename = "keep-monthly")]
    KeepMonthly,
    #[serde(rename = "keep-yearly")]
    KeepYearly,

}

impl std::fmt::Display for PbsConfigPruneInlineEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Comment => write!(f, "comment"),
            Self::Disable => write!(f, "disable"),
            Self::Ns => write!(f, "ns"),
            Self::MaxDepth => write!(f, "max-depth"),
            Self::KeepLast => write!(f, "keep-last"),
            Self::KeepHourly => write!(f, "keep-hourly"),
            Self::KeepDaily => write!(f, "keep-daily"),
            Self::KeepWeekly => write!(f, "keep-weekly"),
            Self::KeepMonthly => write!(f, "keep-monthly"),
            Self::KeepYearly => write!(f, "keep-yearly"),
        }
    }
}

impl Default for PbsConfigPruneInlineEnum {
    fn default() -> PbsConfigPruneInlineEnum {
        Self::Comment
    }
}

