/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PbsProviderQuirksEnum {
    #[serde(rename = "skip-if-none-match-header")]
    SkipIfNoneMatchHeader,
    #[serde(rename = "delete-objects-via-delete-object")]
    DeleteObjectsViaDeleteObject,

}

impl std::fmt::Display for PbsProviderQuirksEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::SkipIfNoneMatchHeader => write!(f, "skip-if-none-match-header"),
            Self::DeleteObjectsViaDeleteObject => write!(f, "delete-objects-via-delete-object"),
        }
    }
}

impl Default for PbsProviderQuirksEnum {
    fn default() -> PbsProviderQuirksEnum {
        Self::SkipIfNoneMatchHeader
    }
}

