/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PbsConfigRemoteInlineEnum {
    #[serde(rename = "comment")]
    Comment,
    #[serde(rename = "fingerprint")]
    Fingerprint,
    #[serde(rename = "port")]
    Port,
    #[serde(rename = "use-node-proxy")]
    UseNodeProxy,

}

impl std::fmt::Display for PbsConfigRemoteInlineEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Comment => write!(f, "comment"),
            Self::Fingerprint => write!(f, "fingerprint"),
            Self::Port => write!(f, "port"),
            Self::UseNodeProxy => write!(f, "use-node-proxy"),
        }
    }
}

impl Default for PbsConfigRemoteInlineEnum {
    fn default() -> PbsConfigRemoteInlineEnum {
        Self::Comment
    }
}

