/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PbsNodesAptInlineEnum {
    #[serde(rename = "deb")]
    Deb,
    #[serde(rename = "deb-src")]
    DebSrc,

}

impl std::fmt::Display for PbsNodesAptInlineEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Deb => write!(f, "deb"),
            Self::DebSrc => write!(f, "deb-src"),
        }
    }
}

impl Default for PbsNodesAptInlineEnum {
    fn default() -> PbsNodesAptInlineEnum {
        Self::Deb
    }
}

