/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PbsRoleidEnum {
    #[serde(rename = "Admin")]
    Admin,
    #[serde(rename = "Audit")]
    Audit,
    #[serde(rename = "NoAccess")]
    NoAccess,
    #[serde(rename = "DatastoreAdmin")]
    DatastoreAdmin,
    #[serde(rename = "DatastoreReader")]
    DatastoreReader,
    #[serde(rename = "DatastoreBackup")]
    DatastoreBackup,
    #[serde(rename = "DatastorePowerUser")]
    DatastorePowerUser,
    #[serde(rename = "DatastoreAudit")]
    DatastoreAudit,
    #[serde(rename = "RemoteAudit")]
    RemoteAudit,
    #[serde(rename = "RemoteAdmin")]
    RemoteAdmin,
    #[serde(rename = "RemoteSyncOperator")]
    RemoteSyncOperator,
    #[serde(rename = "RemoteSyncPushOperator")]
    RemoteSyncPushOperator,
    #[serde(rename = "RemoteDatastorePowerUser")]
    RemoteDatastorePowerUser,
    #[serde(rename = "RemoteDatastoreAdmin")]
    RemoteDatastoreAdmin,
    #[serde(rename = "TapeAudit")]
    TapeAudit,
    #[serde(rename = "TapeAdmin")]
    TapeAdmin,
    #[serde(rename = "TapeOperator")]
    TapeOperator,
    #[serde(rename = "TapeReader")]
    TapeReader,

}

impl std::fmt::Display for PbsRoleidEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Admin => write!(f, "Admin"),
            Self::Audit => write!(f, "Audit"),
            Self::NoAccess => write!(f, "NoAccess"),
            Self::DatastoreAdmin => write!(f, "DatastoreAdmin"),
            Self::DatastoreReader => write!(f, "DatastoreReader"),
            Self::DatastoreBackup => write!(f, "DatastoreBackup"),
            Self::DatastorePowerUser => write!(f, "DatastorePowerUser"),
            Self::DatastoreAudit => write!(f, "DatastoreAudit"),
            Self::RemoteAudit => write!(f, "RemoteAudit"),
            Self::RemoteAdmin => write!(f, "RemoteAdmin"),
            Self::RemoteSyncOperator => write!(f, "RemoteSyncOperator"),
            Self::RemoteSyncPushOperator => write!(f, "RemoteSyncPushOperator"),
            Self::RemoteDatastorePowerUser => write!(f, "RemoteDatastorePowerUser"),
            Self::RemoteDatastoreAdmin => write!(f, "RemoteDatastoreAdmin"),
            Self::TapeAudit => write!(f, "TapeAudit"),
            Self::TapeAdmin => write!(f, "TapeAdmin"),
            Self::TapeOperator => write!(f, "TapeOperator"),
            Self::TapeReader => write!(f, "TapeReader"),
        }
    }
}

impl Default for PbsRoleidEnum {
    fn default() -> PbsRoleidEnum {
        Self::Admin
    }
}

