/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PbsNodesDisksRaidlevelEnum {
    #[serde(rename = "single")]
    Single,
    #[serde(rename = "mirror")]
    Mirror,
    #[serde(rename = "raid10")]
    Raid10,
    #[serde(rename = "raidz")]
    Raidz,
    #[serde(rename = "raidz2")]
    Raidz2,
    #[serde(rename = "raidz3")]
    Raidz3,

}

impl std::fmt::Display for PbsNodesDisksRaidlevelEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Single => write!(f, "single"),
            Self::Mirror => write!(f, "mirror"),
            Self::Raid10 => write!(f, "raid10"),
            Self::Raidz => write!(f, "raidz"),
            Self::Raidz2 => write!(f, "raidz2"),
            Self::Raidz3 => write!(f, "raidz3"),
        }
    }
}

impl Default for PbsNodesDisksRaidlevelEnum {
    fn default() -> PbsNodesDisksRaidlevelEnum {
        Self::Single
    }
}

