/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PbsUsageTypeEnum {
    #[serde(rename = "unused")]
    Unused,
    #[serde(rename = "mounted")]
    Mounted,
    #[serde(rename = "lvm")]
    Lvm,
    #[serde(rename = "zfs")]
    Zfs,
    #[serde(rename = "devicemapper")]
    Devicemapper,
    #[serde(rename = "partitions")]
    Partitions,
    #[serde(rename = "filesystem")]
    Filesystem,

}

impl std::fmt::Display for PbsUsageTypeEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Unused => write!(f, "unused"),
            Self::Mounted => write!(f, "mounted"),
            Self::Lvm => write!(f, "lvm"),
            Self::Zfs => write!(f, "zfs"),
            Self::Devicemapper => write!(f, "devicemapper"),
            Self::Partitions => write!(f, "partitions"),
            Self::Filesystem => write!(f, "filesystem"),
        }
    }
}

impl Default for PbsUsageTypeEnum {
    fn default() -> PbsUsageTypeEnum {
        Self::Unused
    }
}

