/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PbsConfigVerifyInlineEnum {
    #[serde(rename = "ignore-verified")]
    IgnoreVerified,
    #[serde(rename = "comment")]
    Comment,
    #[serde(rename = "schedule")]
    Schedule,
    #[serde(rename = "outdated-after")]
    OutdatedAfter,
    #[serde(rename = "ns")]
    Ns,
    #[serde(rename = "max-depth")]
    MaxDepth,
    #[serde(rename = "read-threads")]
    ReadThreads,
    #[serde(rename = "verify-threads")]
    VerifyThreads,

}

impl std::fmt::Display for PbsConfigVerifyInlineEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::IgnoreVerified => write!(f, "ignore-verified"),
            Self::Comment => write!(f, "comment"),
            Self::Schedule => write!(f, "schedule"),
            Self::OutdatedAfter => write!(f, "outdated-after"),
            Self::Ns => write!(f, "ns"),
            Self::MaxDepth => write!(f, "max-depth"),
            Self::ReadThreads => write!(f, "read-threads"),
            Self::VerifyThreads => write!(f, "verify-threads"),
        }
    }
}

impl Default for PbsConfigVerifyInlineEnum {
    fn default() -> PbsConfigVerifyInlineEnum {
        Self::IgnoreVerified
    }
}

