/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PbsConfigNotificationsInlineEnum4 {
    #[serde(rename = "comment")]
    Comment,
    #[serde(rename = "disable")]
    Disable,
    #[serde(rename = "header")]
    Header,
    #[serde(rename = "body")]
    Body,
    #[serde(rename = "secret")]
    Secret,

}

impl std::fmt::Display for PbsConfigNotificationsInlineEnum4 {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Comment => write!(f, "comment"),
            Self::Disable => write!(f, "disable"),
            Self::Header => write!(f, "header"),
            Self::Body => write!(f, "body"),
            Self::Secret => write!(f, "secret"),
        }
    }
}

impl Default for PbsConfigNotificationsInlineEnum4 {
    fn default() -> PbsConfigNotificationsInlineEnum4 {
        Self::Comment
    }
}

