/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PbsAdminDatastoreStateEnum {
    #[serde(rename = "ok")]
    Ok,
    #[serde(rename = "failed")]
    Failed,

}

impl std::fmt::Display for PbsAdminDatastoreStateEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Ok => write!(f, "ok"),
            Self::Failed => write!(f, "failed"),
        }
    }
}

impl Default for PbsAdminDatastoreStateEnum {
    fn default() -> PbsAdminDatastoreStateEnum {
        Self::Ok
    }
}

