/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PbsConfigNotificationsInlineEnum5 {
    #[serde(rename = "comment")]
    Comment,
    #[serde(rename = "disable")]
    Disable,
    #[serde(rename = "invert-match")]
    InvertMatch,
    #[serde(rename = "match-calendar")]
    MatchCalendar,
    #[serde(rename = "match-field")]
    MatchField,
    #[serde(rename = "match-severity")]
    MatchSeverity,
    #[serde(rename = "mode")]
    Mode,
    #[serde(rename = "target")]
    Target,

}

impl std::fmt::Display for PbsConfigNotificationsInlineEnum5 {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Comment => write!(f, "comment"),
            Self::Disable => write!(f, "disable"),
            Self::InvertMatch => write!(f, "invert-match"),
            Self::MatchCalendar => write!(f, "match-calendar"),
            Self::MatchField => write!(f, "match-field"),
            Self::MatchSeverity => write!(f, "match-severity"),
            Self::Mode => write!(f, "mode"),
            Self::Target => write!(f, "target"),
        }
    }
}

impl Default for PbsConfigNotificationsInlineEnum5 {
    fn default() -> PbsConfigNotificationsInlineEnum5 {
        Self::Comment
    }
}

