/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PbsActivityEnum {
    #[serde(rename = "no-activity")]
    NoActivity,
    #[serde(rename = "cleaning")]
    Cleaning,
    #[serde(rename = "loading")]
    Loading,
    #[serde(rename = "unloading")]
    Unloading,
    #[serde(rename = "other")]
    Other,
    #[serde(rename = "reading")]
    Reading,
    #[serde(rename = "writing")]
    Writing,
    #[serde(rename = "locating")]
    Locating,
    #[serde(rename = "rewinding")]
    Rewinding,
    #[serde(rename = "erasing")]
    Erasing,
    #[serde(rename = "formatting")]
    Formatting,
    #[serde(rename = "calibrating")]
    Calibrating,
    #[serde(rename = "other-d-t")]
    OtherDT,
    #[serde(rename = "microcode-update")]
    MicrocodeUpdate,
    #[serde(rename = "reading-encrypted")]
    ReadingEncrypted,
    #[serde(rename = "writing-encrypted")]
    WritingEncrypted,

}

impl std::fmt::Display for PbsActivityEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::NoActivity => write!(f, "no-activity"),
            Self::Cleaning => write!(f, "cleaning"),
            Self::Loading => write!(f, "loading"),
            Self::Unloading => write!(f, "unloading"),
            Self::Other => write!(f, "other"),
            Self::Reading => write!(f, "reading"),
            Self::Writing => write!(f, "writing"),
            Self::Locating => write!(f, "locating"),
            Self::Rewinding => write!(f, "rewinding"),
            Self::Erasing => write!(f, "erasing"),
            Self::Formatting => write!(f, "formatting"),
            Self::Calibrating => write!(f, "calibrating"),
            Self::OtherDT => write!(f, "other-d-t"),
            Self::MicrocodeUpdate => write!(f, "microcode-update"),
            Self::ReadingEncrypted => write!(f, "reading-encrypted"),
            Self::WritingEncrypted => write!(f, "writing-encrypted"),
        }
    }
}

impl Default for PbsActivityEnum {
    fn default() -> PbsActivityEnum {
        Self::NoActivity
    }
}

