/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PbsConfigChangerInlineEnum {
    #[serde(rename = "export-slots")]
    ExportSlots,
    #[serde(rename = "eject-before-unload")]
    EjectBeforeUnload,

}

impl std::fmt::Display for PbsConfigChangerInlineEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::ExportSlots => write!(f, "export-slots"),
            Self::EjectBeforeUnload => write!(f, "eject-before-unload"),
        }
    }
}

impl Default for PbsConfigChangerInlineEnum {
    fn default() -> PbsConfigChangerInlineEnum {
        Self::ExportSlots
    }
}

