/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PbsConfigAccessInlineEnum2 {
    #[serde(rename = "origin")]
    Origin,
    #[serde(rename = "allow-subdomains")]
    AllowSubdomains,

}

impl std::fmt::Display for PbsConfigAccessInlineEnum2 {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Origin => write!(f, "origin"),
            Self::AllowSubdomains => write!(f, "allow-subdomains"),
        }
    }
}

impl Default for PbsConfigAccessInlineEnum2 {
    fn default() -> PbsConfigAccessInlineEnum2 {
        Self::Origin
    }
}

