/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TapeDriveCreateRestoreKeyRequest {

    /// The password the key was encrypted with.
    #[serde(rename = "password")]
    pub password: String,


}

impl TapeDriveCreateRestoreKeyRequest {
    pub fn new(password: String) -> TapeDriveCreateRestoreKeyRequest {
        TapeDriveCreateRestoreKeyRequest {
            
            password,
            
        }
    }
}


