/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TapeChangerGetChangerResponseDataInner {

    /// if set to true, tapes are ejected manually before unloading
    #[serde(rename = "eject-before-unload", skip_serializing_if = "Option::is_none")]
    pub eject_before_unload: Option<bool>,

    /// A list of slot numbers, comma separated. Those slots are reserved for Import/Export, i.e. any media in those slots are considered to be 'offline'. 
    #[serde(rename = "export-slots", skip_serializing_if = "Option::is_none")]
    pub export_slots: Option<Box<models::PbsExportSlotsField>>,

    /// Model (autodetected)
    #[serde(rename = "model", skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,

    /// Tape Changer Identifier.
    #[serde(rename = "name")]
    pub name: String,

    /// Path to Linux generic SCSI device (e.g. '/dev/sg4')
    #[serde(rename = "path")]
    pub path: String,

    /// Serial number (autodetected)
    #[serde(rename = "serial", skip_serializing_if = "Option::is_none")]
    pub serial: Option<String>,

    /// Vendor (autodetected)
    #[serde(rename = "vendor", skip_serializing_if = "Option::is_none")]
    pub vendor: Option<String>,


}

impl TapeChangerGetChangerResponseDataInner {
    pub fn new(name: String, path: String) -> TapeChangerGetChangerResponseDataInner {
        TapeChangerGetChangerResponseDataInner {
            
            eject_before_unload: None,
            
            export_slots: None,
            
            model: None,
            
            name,
            
            path,
            
            serial: None,
            
            vendor: None,
            
        }
    }
}


