/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TapeDriveCreateCatalogRequest {

    /// Force overriding existing index.
    #[serde(rename = "force", skip_serializing_if = "Option::is_none")]
    pub force: Option<bool>,

    /// Re-read the whole tape to reconstruct the catalog instead of restoring saved versions.
    #[serde(rename = "scan", skip_serializing_if = "Option::is_none")]
    pub scan: Option<bool>,

    /// Verbose mode - log all found chunks.
    #[serde(rename = "verbose", skip_serializing_if = "Option::is_none")]
    pub verbose: Option<bool>,


}

impl TapeDriveCreateCatalogRequest {
    pub fn new() -> TapeDriveCreateCatalogRequest {
        TapeDriveCreateCatalogRequest {
            
            force: None,
            
            scan: None,
            
            verbose: None,
            
        }
    }
}


