/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TapeDriveGetInventoryResponseDataInner {

    /// Changer label text (or Barcode)
    #[serde(rename = "label-text")]
    pub label_text: String,

    /// Media Uuid.
    #[serde(rename = "uuid", skip_serializing_if = "Option::is_none")]
    pub uuid: Option<String>,


}

impl TapeDriveGetInventoryResponseDataInner {
    pub fn new(label_text: String) -> TapeDriveGetInventoryResponseDataInner {
        TapeDriveGetInventoryResponseDataInner {
            
            label_text,
            
            uuid: None,
            
        }
    }
}


