/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TapeDriveUpdateInventoryRequest {

    /// Restore the catalog from tape.
    #[serde(rename = "catalog", skip_serializing_if = "Option::is_none")]
    pub catalog: Option<bool>,

    /// Load all tapes and try read labels (even if already inventoried)
    #[serde(rename = "read-all-labels", skip_serializing_if = "Option::is_none")]
    pub read_all_labels: Option<bool>,


}

impl TapeDriveUpdateInventoryRequest {
    pub fn new() -> TapeDriveUpdateInventoryRequest {
        TapeDriveUpdateInventoryRequest {
            
            catalog: None,
            
            read_all_labels: None,
            
        }
    }
}


