/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TapeDriveCreateUnloadRequest {

    /// Target slot number. If omitted, defaults to the slot that the drive was loaded from.
    #[serde(rename = "target-slot", skip_serializing_if = "Option::is_none")]
    pub target_slot: Option<i64>,


}

impl TapeDriveCreateUnloadRequest {
    pub fn new() -> TapeDriveCreateUnloadRequest {
        TapeDriveCreateUnloadRequest {
            
            target_slot: None,
            
        }
    }
}


