/*
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VersionGetVersionResponseData {

    /// Version release
    #[serde(rename = "release")]
    pub release: String,

    /// Version repository id
    #[serde(rename = "repoid")]
    pub repoid: String,

    /// Version 'major.minor'
    #[serde(rename = "version")]
    pub version: String,


}

impl VersionGetVersionResponseData {
    pub fn new(release: String, repoid: String, version: String) -> VersionGetVersionResponseData {
        VersionGetVersionResponseData {
            
            release,
            
            repoid,
            
            version,
            
        }
    }
}


